FROM nginx:1.27-alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf

WORKDIR /var/www

COPY ./public /var/www/public

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]